-- =============================================================================
-- Retail Sales & Inventory Analytics System : PostgreSQL schema
-- Re-runnable: drops and recreates all objects.
-- Currency: INR. All data is synthetic.
--
-- Design notes
--  * Surrogate keys use GENERATED BY DEFAULT AS IDENTITY so bulk loads (COPY)
--    can supply explicit IDs; sequences are re-synced after loading.
--  * CHECK constraints block impossible values (negative price, qty <= 0).
--    Softer quality problems (duplicate-like customers, bad e-mail formats,
--    NULL supplier) are deliberately NOT blocked: real source systems allow
--    them, and the data-quality queries exist to detect them.
-- =============================================================================

-- ---- clean slate (children first) -------------------------------------------
DROP TABLE IF EXISTS return_items          CASCADE;
DROP TABLE IF EXISTS returns               CASCADE;
DROP TABLE IF EXISTS payments              CASCADE;
DROP TABLE IF EXISTS sales_order_items     CASCADE;
DROP TABLE IF EXISTS sales_orders          CASCADE;
DROP TABLE IF EXISTS product_promotions    CASCADE;
DROP TABLE IF EXISTS promotions            CASCADE;
DROP TABLE IF EXISTS purchase_items        CASCADE;
DROP TABLE IF EXISTS purchases             CASCADE;
DROP TABLE IF EXISTS inventory_transactions CASCADE;
DROP TABLE IF EXISTS inventory             CASCADE;
DROP TABLE IF EXISTS employees             CASCADE;
DROP TABLE IF EXISTS stores                CASCADE;
DROP TABLE IF EXISTS products              CASCADE;
DROP TABLE IF EXISTS suppliers             CASCADE;
DROP TABLE IF EXISTS categories            CASCADE;
DROP TABLE IF EXISTS customers             CASCADE;
DROP TABLE IF EXISTS customer_segments     CASCADE;
DROP TABLE IF EXISTS dim_date              CASCADE;
DROP FUNCTION IF EXISTS set_updated_at()   CASCADE;

-- ---- reusable trigger function: keeps updated_at honest ----------------------
CREATE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =============================================================================
-- REFERENCE / DIMENSION TABLES
-- =============================================================================

-- Calendar table (populated in seed_data.sql). Useful for Power BI time intelligence.
CREATE TABLE dim_date (
    date_key        DATE PRIMARY KEY,
    year            SMALLINT NOT NULL,
    quarter         SMALLINT NOT NULL CHECK (quarter BETWEEN 1 AND 4),
    month           SMALLINT NOT NULL CHECK (month BETWEEN 1 AND 12),
    month_name      VARCHAR(10) NOT NULL,
    year_month      CHAR(7) NOT NULL,            -- 'YYYY-MM'
    week_of_year    SMALLINT NOT NULL,
    day_of_month    SMALLINT NOT NULL,
    day_of_week     SMALLINT NOT NULL,           -- 1 = Monday
    day_name        VARCHAR(10) NOT NULL,
    is_weekend      BOOLEAN NOT NULL
);

CREATE TABLE customer_segments (
    segment_id      SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    segment_name    VARCHAR(50) NOT NULL UNIQUE,
    description     TEXT
);

CREATE TABLE categories (
    category_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name   VARCHAR(100) NOT NULL UNIQUE,   -- case-sensitive uniqueness on purpose
    parent_category_id INT REFERENCES categories(category_id),  -- self-reference (hierarchy)
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE suppliers (
    supplier_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_name   VARCHAR(150) NOT NULL,
    contact_email   VARCHAR(150),
    contact_phone   VARCHAR(20),
    city            VARCHAR(80),
    state           VARCHAR(80),
    gstin           CHAR(15),                        -- Indian GST identification number
    lead_time_days  SMALLINT NOT NULL DEFAULT 7 CHECK (lead_time_days BETWEEN 0 AND 120),
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE products (
    product_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku             VARCHAR(30) NOT NULL UNIQUE,
    product_name    VARCHAR(200) NOT NULL,
    brand           VARCHAR(80),
    category_id     INT REFERENCES categories(category_id),   -- nullable: DQ scenario
    supplier_id     INT REFERENCES suppliers(supplier_id),    -- nullable: DQ scenario
    unit_cost       NUMERIC(12,2) NOT NULL CHECK (unit_cost >= 0),
    unit_price      NUMERIC(12,2) NOT NULL CHECK (unit_price >= 0),  -- MRP, GST-inclusive
    gst_rate        NUMERIC(4,2)  NOT NULL DEFAULT 18 CHECK (gst_rate IN (0, 5, 12, 18, 28)),
    launch_date     DATE,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE stores (
    store_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_code      VARCHAR(10) NOT NULL UNIQUE,
    store_name      VARCHAR(120) NOT NULL,
    store_type      VARCHAR(20) NOT NULL DEFAULT 'STORE'
                    CHECK (store_type IN ('STORE', 'ONLINE_WAREHOUSE')),
    city            VARCHAR(80) NOT NULL,
    state           VARCHAR(80) NOT NULL,
    region          VARCHAR(20) NOT NULL CHECK (region IN ('North','South','East','West','Central')),
    opened_date     DATE NOT NULL,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE employees (
    employee_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name      VARCHAR(60) NOT NULL,
    last_name       VARCHAR(60),
    email           VARCHAR(150),
    store_id        INT NOT NULL REFERENCES stores(store_id),
    manager_id      INT REFERENCES employees(employee_id),    -- self-reference
    job_title       VARCHAR(60) NOT NULL,
    hire_date       DATE NOT NULL,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE customers (
    customer_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name      VARCHAR(60) NOT NULL,
    last_name       VARCHAR(60),
    email           VARCHAR(150),        -- not UNIQUE: duplicate-like rows exist on purpose
    phone           VARCHAR(20),
    gender          CHAR(1) CHECK (gender IN ('M', 'F', 'O')),
    date_of_birth   DATE,
    city            VARCHAR(80),
    state           VARCHAR(80),
    segment_id      SMALLINT REFERENCES customer_segments(segment_id),
    registration_date DATE NOT NULL,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP NOT NULL DEFAULT now()
);

-- =============================================================================
-- PROMOTIONS  (many-to-many with products)
-- =============================================================================
CREATE TABLE promotions (
    promotion_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promo_code      VARCHAR(30) NOT NULL UNIQUE,
    promo_name      VARCHAR(120) NOT NULL,
    discount_type   VARCHAR(10) NOT NULL CHECK (discount_type IN ('PERCENT', 'FLAT')),
    discount_value  NUMERIC(10,2) NOT NULL CHECK (discount_value > 0),
    start_date      DATE NOT NULL,
    end_date        DATE NOT NULL,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT chk_promo_dates CHECK (end_date >= start_date),
    CONSTRAINT chk_promo_percent CHECK (discount_type <> 'PERCENT' OR discount_value <= 90)
);

CREATE TABLE product_promotions (
    promotion_id    INT NOT NULL REFERENCES promotions(promotion_id),
    product_id      INT NOT NULL REFERENCES products(product_id),
    PRIMARY KEY (promotion_id, product_id)          -- composite key = junction table
);

-- =============================================================================
-- SALES
-- =============================================================================
CREATE TABLE sales_orders (
    order_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number    VARCHAR(20) NOT NULL UNIQUE,
    customer_id     INT NOT NULL REFERENCES customers(customer_id),
    store_id        INT NOT NULL REFERENCES stores(store_id),
    employee_id     INT REFERENCES employees(employee_id),   -- NULL for online orders
    order_date      TIMESTAMP NOT NULL,
    channel         VARCHAR(10) NOT NULL DEFAULT 'IN_STORE' CHECK (channel IN ('IN_STORE', 'ONLINE')),
    order_status    VARCHAR(20) NOT NULL DEFAULT 'COMPLETED'
                    CHECK (order_status IN ('COMPLETED', 'CANCELLED')),
    -- Prices are GST-inclusive (Indian MRP). Net revenue = total_amount - gst_amount.
    subtotal        NUMERIC(12,2) NOT NULL CHECK (subtotal >= 0),   -- sum(quantity * unit_price) before discount
    discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    gst_amount      NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (gst_amount >= 0),  -- GST portion contained in total_amount
    total_amount    NUMERIC(12,2) NOT NULL CHECK (total_amount >= 0),          -- subtotal - discount_amount
    created_at      TIMESTAMP NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE sales_order_items (
    order_item_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        INT NOT NULL REFERENCES sales_orders(order_id),
    product_id      INT NOT NULL REFERENCES products(product_id),
    promotion_id    INT REFERENCES promotions(promotion_id),
    quantity        INT NOT NULL CHECK (quantity > 0),
    unit_price      NUMERIC(12,2) NOT NULL CHECK (unit_price >= 0),   -- price charged at sale time
    unit_cost       NUMERIC(12,2) NOT NULL CHECK (unit_cost >= 0),    -- cost snapshot at sale time (for profit)
    discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),  -- total discount on this line
    line_total      NUMERIC(12,2) NOT NULL CHECK (line_total >= 0),   -- quantity*unit_price - discount_amount
    UNIQUE (order_id, product_id)
);

CREATE TABLE payments (
    payment_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        INT NOT NULL REFERENCES sales_orders(order_id),
    payment_date    TIMESTAMP NOT NULL,
    payment_method  VARCHAR(15) NOT NULL
                    CHECK (payment_method IN ('UPI', 'CARD', 'CASH', 'NET_BANKING', 'WALLET')),
    amount          NUMERIC(12,2) NOT NULL CHECK (amount > 0),
    payment_status  VARCHAR(10) NOT NULL DEFAULT 'SUCCESS'
                    CHECK (payment_status IN ('SUCCESS', 'FAILED', 'REFUNDED')),
    transaction_ref VARCHAR(40),
    created_at      TIMESTAMP NOT NULL DEFAULT now()
);

-- =============================================================================
-- RETURNS
-- =============================================================================
CREATE TABLE returns (
    return_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        INT NOT NULL REFERENCES sales_orders(order_id),
    return_date     TIMESTAMP NOT NULL,
    return_reason   VARCHAR(30) NOT NULL
                    CHECK (return_reason IN ('DEFECTIVE', 'WRONG_ITEM', 'NOT_AS_DESCRIBED',
                                             'CHANGED_MIND', 'SIZE_ISSUE', 'DAMAGED_IN_TRANSIT', 'OTHER')),
    refund_amount   NUMERIC(12,2) NOT NULL CHECK (refund_amount >= 0),
    processed_by    INT REFERENCES employees(employee_id),
    created_at      TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE return_items (
    return_item_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_id       INT NOT NULL REFERENCES returns(return_id),
    order_item_id   INT NOT NULL REFERENCES sales_order_items(order_item_id),
    quantity        INT NOT NULL CHECK (quantity > 0),
    refund_amount   NUMERIC(12,2) NOT NULL CHECK (refund_amount >= 0),
    restocked       BOOLEAN NOT NULL DEFAULT TRUE,     -- FALSE = written off (e.g. defective)
    UNIQUE (return_id, order_item_id)
);

-- =============================================================================
-- INVENTORY & PROCUREMENT
-- =============================================================================
CREATE TABLE inventory (
    inventory_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id        INT NOT NULL REFERENCES stores(store_id),
    product_id      INT NOT NULL REFERENCES products(product_id),
    quantity_on_hand INT NOT NULL DEFAULT 0 CHECK (quantity_on_hand >= 0),
    reserved_quantity INT NOT NULL DEFAULT 0 CHECK (reserved_quantity >= 0),
    reorder_level   INT NOT NULL DEFAULT 10 CHECK (reorder_level >= 0),
    max_stock_level INT NOT NULL DEFAULT 200 CHECK (max_stock_level > 0),
    last_restocked_date DATE,
    updated_at      TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (store_id, product_id),                       -- one row per product per store
    CONSTRAINT chk_reserved_le_onhand CHECK (reserved_quantity <= quantity_on_hand)
);

-- Ledger of every stock movement. Sum(quantity_change) per store+product
-- should equal inventory.quantity_on_hand (checked in data-quality queries).
CREATE TABLE inventory_transactions (
    transaction_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id        INT NOT NULL REFERENCES stores(store_id),
    product_id      INT NOT NULL REFERENCES products(product_id),
    transaction_type VARCHAR(12) NOT NULL
                    CHECK (transaction_type IN ('OPENING', 'PURCHASE', 'SALE', 'RETURN', 'ADJUSTMENT')),
    quantity_change INT NOT NULL CHECK (quantity_change <> 0),   -- + adds stock, - removes stock
    transaction_date TIMESTAMP NOT NULL,
    reference_type  VARCHAR(20),      -- 'PURCHASE', 'SALES_ORDER', 'RETURN' or NULL
    reference_id    INT,              -- polymorphic reference, so no FK by design
    created_at      TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE purchases (
    purchase_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_number       VARCHAR(20) NOT NULL UNIQUE,
    supplier_id     INT NOT NULL REFERENCES suppliers(supplier_id),
    store_id        INT NOT NULL REFERENCES stores(store_id),      -- receiving store
    order_date      DATE NOT NULL,
    expected_date   DATE NOT NULL,
    received_date   DATE,                                           -- NULL until received
    status          VARCHAR(12) NOT NULL DEFAULT 'RECEIVED'
                    CHECK (status IN ('ORDERED', 'RECEIVED', 'CANCELLED')),
    total_amount    NUMERIC(14,2) NOT NULL CHECK (total_amount >= 0),
    created_at      TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT chk_po_dates CHECK (expected_date >= order_date
                                   AND (received_date IS NULL OR received_date >= order_date))
);

CREATE TABLE purchase_items (
    purchase_item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_id     INT NOT NULL REFERENCES purchases(purchase_id),
    product_id      INT NOT NULL REFERENCES products(product_id),
    quantity_ordered INT NOT NULL CHECK (quantity_ordered > 0),
    quantity_received INT NOT NULL DEFAULT 0 CHECK (quantity_received >= 0),
    unit_cost       NUMERIC(12,2) NOT NULL CHECK (unit_cost >= 0),
    UNIQUE (purchase_id, product_id)
);

-- =============================================================================
-- updated_at triggers
-- =============================================================================
CREATE TRIGGER trg_suppliers_upd  BEFORE UPDATE ON suppliers    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_products_upd   BEFORE UPDATE ON products     FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_employees_upd  BEFORE UPDATE ON employees    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_customers_upd  BEFORE UPDATE ON customers    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_orders_upd     BEFORE UPDATE ON sales_orders FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_inventory_upd  BEFORE UPDATE ON inventory    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- NOTE: secondary (performance) indexes are intentionally NOT created here.
-- They live in database/indexes.sql so their effect can be measured with
-- EXPLAIN ANALYZE before/after. PK and UNIQUE constraints already create indexes.
