"""Export dashboard-ready CSV files for Power BI (for people who cannot connect to PostgreSQL directly).

Run from the project root:   python python/export_dashboard_data.py
Files land in dashboard/exported_data/. The CSVs are git-ignored (they are regenerated in a few seconds and the biggest
is ~25 MB); the manifest README.md next to them is committed so the file list and row counts are visible on GitHub.

Table naming follows a star schema so the Power BI model in docs/08_powerbi_dashboard.md can be built directly:
    fact_*  = event tables (many rows)      dim_*  = descriptive tables (few rows)      agg_*  = pre-aggregated views
"""
from datetime import datetime
from pathlib import Path

import pandas as pd

from data_extraction import get_query

DEFAULT_OUT = Path(__file__).resolve().parents[1] / "dashboard" / "exported_data"

# export file -> (SQL, description)
EXPORTS = {
    "fact_sales_lines": ("SELECT * FROM vw_sales_lines", "One row per sold order line (completed orders). Main fact table."),
    "fact_orders": ("SELECT * FROM vw_orders", "One row per order, all statuses (order counts, cancellations, returns flag)."),
    "fact_returns": ("SELECT * FROM vw_return_analysis", "One row per returned order line."),
    "fact_inventory_health": ("SELECT * FROM vw_inventory_health", "Current stock position per store and product, with health status."),
    "dim_date": ("SELECT date_key, year, quarter, month, month_name, year_month, week_of_year, day_of_month, day_of_week, day_name, is_weekend "
                 "FROM dim_date WHERE date_key BETWEEN (SELECT first_order_date FROM vw_asof) AND (SELECT asof_date FROM vw_asof)",
                 "Calendar covering the data window."),
    "dim_store": ("SELECT store_id, store_code, store_name, store_type, city, state, region, opened_date FROM stores", "Stores."),
    "dim_product": ("SELECT * FROM vw_product_performance", "Products with lifetime sales, margin, returns, stock and ABC class."),
    "dim_customer": ("SELECT * FROM vw_customer_summary", "Customers with value, RFM scores and segment."),
    "dim_category": ("SELECT category_id, canonical_id, canonical_name, parent_category FROM vw_category_canonical", "Category lookup (case variants merged)."),
    "agg_monthly_sales": ("SELECT * FROM vw_monthly_sales", "Monthly KPIs."),
    "agg_store_performance": ("SELECT * FROM vw_store_performance", "Store scorecard."),
    "agg_category_performance": ("SELECT * FROM vw_category_performance", "Category by year."),
    "agg_supplier_performance": ("SELECT * FROM vw_supplier_performance", "Supplier scorecard."),
}


def export_all(out_dir: Path = DEFAULT_OUT, engine=None) -> pd.DataFrame:
    """Write every export as CSV and return a manifest DataFrame (file, rows, columns, description)."""
    out_dir.mkdir(parents=True, exist_ok=True)
    rows = []
    for name, (sql, description) in EXPORTS.items():
        df = get_query(sql, engine)
        df.to_csv(out_dir / f"{name}.csv", index=False, date_format="%Y-%m-%d %H:%M:%S")
        rows.append({"file": f"{name}.csv", "rows": len(df), "columns": df.shape[1], "description": description})
    manifest = pd.DataFrame(rows)
    write_manifest(manifest, out_dir)
    return manifest


def write_manifest(manifest: pd.DataFrame, out_dir: Path) -> None:
    lines = ["# Exported dashboard data", "",
             f"Generated by `python python/export_dashboard_data.py` on {datetime.now():%Y-%m-%d}. CSV files are git-ignored; regenerate them any time.", "",
             "| File | Rows | Columns | Content |", "|---|---:|---:|---|"]
    lines += [f"| {r.file} | {r.rows:,} | {r.columns} | {r.description} |" for r in manifest.itertuples()]
    lines += ["", "Amounts are in INR. `net_revenue` excludes GST; `gross_sales_incl_gst` and `total_amount` include it.", ""]
    (out_dir / "README.md").write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    print(export_all().to_string(index=False))
